# config for sensor app

DEVICE_PORT: "COM2"
FAKE_CUSTOM_DATA: 1
SLAVE_ID: 1
BAUDRATE: 921600

TEMP_STABLE_INDICATOR_ADDRESS: 40118
TEMP_STABLE_INDICATOR_VALUE: 2

LASER_CURRENT_LOCK_ADDRESS: 40118
LASER_CURRENT_LOCK_VALUE: 2

RADIO_LOCK_ADDRESS: 40118
RADIO_LOCK_VALUE: 2

START_DEVICE_WRITE_ADDRESS: 40118
START_DEVICE_WRITE_VALUE: 1

INCREASE_TEMP_WRITE_ADDRESS: 40118
INCREASE_TEMP_WRITE_VALUE: 1

LOCK_LASER_WRITE_ADDRESS: 40118
LOCK_LASER_WRITE_VALUE: 2

DDS_WRITE_ADDRESS: 40118
DDS_WRITE_VALUE: 3

CUSTOM_PROTOCO_ADDITIONAL_BYTE_COUNT: 9
CUSTOM_PROTOCO_DATA_BYTE_COUNT: 800
CUSTOM_PROTOCO_FREQUENCY: 200 # 200ms
SLEEP_TIME_MS: 184

DISABLE_CRC: 1

READ_SIN_DATA_CMD: "AB0104753000026A19"
READ_DDS_DATA_CMD: "AB0104791800C86916"

DATA_FREQUENCY: 1000
DATA_PRINT_AVG_COUNT: 10

NUM_DATA_TO_PLOT: 3000

DISPLAY_TIME_RANGE: 15 # in sec
